apiVersion: v1
kind: Pod
metadata:
  name: empty
spec:
  containers:
  - name: nginx
    image: nginx:1.29.1
    volumeMounts:
    - mountPath: /cache
      name: emptii
  volumes:
  - name: emptii
    emptyDir: {}
