apiVersion: v1
kind: Pod
metadata: 
  name: host
spec: 
  containers:
  - name: nginx
    image: nginx:latest
    volumeMounts:
    - mountPath: /home/sarika/data
      name: hostname
  volumes:
  - name: hostname
    hostPath: 
      path: /home/sarika/data
      type: DirectoryOrCreate
