apiVersion: apps/v1
kind: Deployment
metadata:
  name: deploy
  namespace: name-space
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deploy
  template:
    metadata:
      labels:
        app: deploy
    spec: 
      containers:
      - name: nginx
        image: nginx:1.29.1
        ports:
        - containerPort: 80
     